runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /img
  static_dir: img
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: blog.app

libraries:
- name: jinja2
  version: latest